# -*- coding: utf-8 -*-
"""Tarea_2_2_Parte_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1py2D2qBmmVNaVUKPVCUrzEWBQlhtxmyE
"""

import pandas as pd

df = pd.read_csv('./housing.csv')
df.head(30)

df['ocean_proximity'].value_counts()

df.info()

df.describe()

df.hist(figsize=(15,8), bins=50, edgecolor='black')

import seaborn as sb

sb.scatterplot(data=df, x='longitude', y='latitude', hue='median_house_value', palette='coolwarm')

sb.scatterplot(data=df[df['median_income'] > 14], x='longitude', y='latitude', hue='median_house_value', palette='coolwarm')

dumies_ocean_proximity = pd.get_dummies(df['ocean_proximity'], dtype=int)
dumies_ocean_proximity

df = pd.concat([df, dumies_ocean_proximity], axis=1)
df.head()

df.drop(['ocean_proximity'], axis=1, inplace=True)
df.head()

df.dropna(inplace=True)

df.info()

df.corr()

sb.set(rc={'figure.figsize':(15,8)})
sb.heatmap(df.corr(), annot=True, cmap='YlGnBu')

df['bedroom_ratio'] = df['total_rooms'] / df['total_bedrooms']

"""**ENTRENAMIENTO DEL MODELO DE PREDICCIÓN**"""

X = df.drop('median_house_value', axis=1)
y = df['median_house_value']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_train.shape

from sklearn.tree import DecisionTreeClassifier

modelo = DecisionTreeClassifier( max_depth=3 )
model = modelo.fit( X_train, y_train)

predicciones = model.predict(X_test)

predicciones

from sklearn.metrics import accuracy_score

modelo = DecisionTreeClassifier( )
model = modelo.fit( X_train, y_train)
predicciones = model.predict(X_test)
asc = accuracy_score(y_test, predicciones)

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 10))
plot_tree(modelo, filled=True, feature_names=X.columns, max_depth=3)
plt.show()

print(modelo.score(X_train, y_train))
print(modelo.score(X_test, y_test))